---
title: "Design 1"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "What would life cost for your animal, and how hard would it be to be in heat balance?"
date: 2023-09-14
format: 
  html: default 
  pdf: default
  docx: default
categories: [design project, design 1, metabolism, heat balance, DMR, RMR, AMR, SMR, BMR, activity ]
---

# Suggestions for Metabolism and Heat Balance Design

__Look through the analysis below and find the information needed to model__ your animalʻs __metabolism__ and __heat balance__. Hopefully you have it in your background bullet points. Become the expert: find EVERYTHING about your species in the literature, and use the web and library to fill any holes. Ask us or the science librarians for help ASAP. __For example:__ What kind of animal was it? What did it look like? (Please draw the figures yourself, it is part of the learning process). Its position in the tree of life? Where/when did it live?  General environment (think metabolism and heat balance, so climate, humidity, range of ambient temperature, etc.) What other sorts of animals and plants lived at the same time?  Was it an active animal? How did it obtain food? Did it seek cover for shade or hiding places from predators (think how it might impact heat balance and activity)? You want to foreshadow (i.e., hint at) any potential challenges with regard to heat balance (or maybe life was easy in every situation)? Include any info that you find particularly interesting about the animal.  
__Analysis:__ Complete the analysis below using assumptions appropriate for your animal (see sample calculations). Type it up as an appendix of calculations.  Both partners must contribute substantively to finding info and analysis.  
__First draft (due 9/25 by 5pm):__ Include an outline of the intro (organized bullet points of factual information that describes your animal and its metabolism and heat balance problem for a scientific paper), and a complete analysis (appendix). Also include a first draft of the paper. I highly recommend that you __first make an outline__ -- and after completing the full analysis, you write the results and methods, then the discussion, then the intro. Prioritize finishing the analysis, then outline/bullet point your ideas for the discussion and intro, and draft as much as you can.  Give us as much as you can so we can give feedback. __Add citations as you go.__  
__Final draft (due 10/4):__ Will include an introduction, methods, results, discussion, literature cited, appendix, and respective contributions.    
_Note: You are writing a scientific paper (like a scientific journal article — not Q&A)._ Below are content suggestions to help you write an excellent paper (only include aspects that are __relevant__ to your animal):  

- Required: From fossils described in the literature, estimate the body mass and body dimensions of your animal.  Make a sketch of your animal and add the body dimensions (overall height, leg length, wing span, etc).

- Was your animal poikilothermic or homeothermic?  Endothermic or ectothermic? What range of body temperatures could your animal tolerate?  How did it deal with extreme heat or cold stress? If the animal was a thermoregulator, how did it regulate its body temperature? Did it have insulating fur, feathers or fat?  Could it sweat or use other forms of evaporative cooling?  Did it allow its tissues to become supercooled without freezing?  Was it freeze tolerant?  Did it use countercurrent heat exchangers?  Did it go into torpor or hibernate?

- For endotherms, calculate BMR (choose an appropriate interspecific scaling equation from Withers Table 4-5). From BMR, estimate RMR, AMR, MMR and DMR.  What is the metabolic scope of your animal?  Include a lot of detail in writing about the lifestyle of the animal and why you chose the values that you did to estimate DMR and MMR.  

- For ectotherms, choose an appropriate interspecific scaling equation from Withers Table 4-5 and the iterative method to calculate SMR for the animal when it is inactive at night  (assume a Q$_{10}$ of 2.5 for metabolic rate).  How much higher is body temperature than air temperature during the night (T$_b$-T$_a$)?  Use the Q$_{10}$ correction to calculate SMR at the higher ambient temperatures during the day (not yet iterative).  Increase SMR by a factor of 1.5-3 to reflect active metabolic rate (AMR).  Now use the iterative calculations to determine Tb-Ta, and the corresponding increase in MR.  Estimate DMR for your animal. These are just suggestions, find something interesting about DMR to explore.

- Estimate values for the heat balance equation for your animal at rest.  Use allometric equations to estimate minimum Hc, and CEWL+REWL to estimate minimum He.  Then imagine some situations in which your animal might experience heat or cold stress, and use the heat equation to see whether it is able to maintain heat balance.  Create a situation that would put your animal out of heat balance.  _How fast does the body temperature increase or decrease?_  

- If your animal is an endotherm, how much energy per day could your animal save by hibernating with a lower body temperature (if reasonable for your animal; this is a hard question to answer).

:::{.callout-note}
# Note:  Use standard scientific citation and reference formats throughout all of your papers.  

Cite sources as (author(s), date) and include full references at the end of each design. For example:  The earliest amphibians were largely aquatic, and are thought to have had internal gills (Coates and Clack, 1991).

Coates, M. I. and Clack, J. A. 1991. Fish-like gills and breathing in the earliest known tetrapod. _Nature_, 352:234-236.
:::

\[[pdf](1.MetabolismTempDesign1.pdf)\] version of this sheet