---
title: "5\\. Feeding"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Food! Glorious food!"
date: 2023-09-18
format: 
  html: default 
  pdf: default
categories: [module 5, week 5, food, feeding, nutrient composition, DMR]
---

This week will be a little odd. Monday we will do the Sustained metabolic scope discussion originally scheduled for last Friday. Wednesday we will start talking about feeding (our favorite topic!) and digestion. Friday we will have a special treat - Allison will lead a workshop to help you improve your design 1 drafts.  Bring your drafts!  

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Monday we will discuss \[[Metabolic Celings](../../discussions/Discussion-Week4-metabolic-ceiling.pdf)\] 
2. Wednesday we will start Feeding & Digestion \[[discussion](../../discussions/Discussion-Week5-feeding-digestion.pdf)\]
3. Friday Design 1 draft workshop! With Allison
:::

### Announcements/Reminders

-  This will be our first toad lab. Please wear shoes and bring your dissection kit (if you have one, if not we will provide).
-  Do discussion TEAMMATES eval, released each Friday, due by Monday.

### Week 5 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
| 1 |Adry| Logan M  | Alvin |
| 2 |  Krystal  |  Garrett | Richard |
| 3 | Sasha |  Mayuka | Matt |
| 4 | Logan B  | Kylie  | Morgan |
| 5 |  Anna | Maisie  | Christina |
| 6 |  Kirsten  | Justin  |  |

## Snakes Drink Weird!

{{< video https://youtu.be/_r3gG6NjNKQ >}}

## Monday
   
- Paper discussion

## Wednesday

- Feeding & Digestion Q1-2

## Friday 

- Design 1 Workshop


# For Next Time

::: callout-note
## Reminders and materials
- Next week letʻs find a common lab time for design critique session. <https://lettucemeet.com/l/Obd3q>
- You should have all of your background information and should be completing your analysis. 
- Make an appointment for you and your partner to get help from me. Both must attend. <https://calendly.com/mbutler808/office-hours>

:::


