---
title: "3\\. Temperature"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Heat and its implications for physiology"
date: 2023-09-06
format: 
  html: default 
  pdf: default
categories: [module 3, week 3, BMR, SMR, RMR, AMR, DMR ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Withers chapter 5. Look over the homework, handout, and discussion questions and skim the chapter, reading anything that you need to know. 
2. \[[Discussion Questions](../../discussions/Discussion_Week_3_temperature.pdf)\] 
3. \[[Slide Deck](../../powerpoints/3.Temperature.pdf)\] - for your reference as we go through the material
:::

### Announcements/Reminders

-  Monday is Labor Day. No class


### Week 3 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
| 1 | Justin  | Morgan  | Richard |
| 2 | Adry   |  Matthew | Logan B |
| 3 | Mayuka |  Krystal | Logan M |
| 4 | Anna  | Garrett  | Sasha |
| 5 | Kirsten  | Christina  | Kylie |
| 6 | Maisie   | Alvin  |  |
   

:::{.callout-tip}
# Thought for the day

> Physiology is the story of evolution’s struggle to maintain an appropriate SA/D ratio in relation to the volume of an animal -- _Haldane_ 
:::
   
# 3. Temperature

## Modes of Heat Transfer

- __Conduction__
- __Convection__
- __Evaporative__
- __Radiative__

Animals also generate heat through __Metabolism__.

{{< video https://youtu.be/BHchDrboqEo >}}



Flux = C * $\nabla$ (Mass or Energy) 

Q = C * M $\nabla$ T

Where:
- Flux is the transfer of mass or energy
- $\nabla$ is the gradient symbol
- Q is heat
- C is a material property (resistance or insulation value)
- T is temperature

## Heat Balance 

Metbolic heat production is balanced by all mechanisms for heat exchange: 

$\Delta$H$_s$ = H$_m$ $\pm$ H$_c$ $\pm$ H$_r$ $\pm$ H$_e$

Where:  
$\Delta$H$_s$ = heat of storage  
H$_m$ = heat of metabolism  
H$_c$ = heat of conduction and convection  
H$_r$ = heat of radiation  
H$_e$ = heat of evaporation  

If an animal is in heat balance, Tb (body temperature) is stable. 

If $\Delta$H$_s$ is positive,  (Gains > Losses), then  Tb increases.  

If $\Delta$H$_s$ is negative,  (Gains < Losses), then  Tb decreases.  


## Body Temperature


## Q10 

{{< video https://youtu.be/T5O9UvSZ_-g >}}

## Iterative Method

{{< video https://youtu.be/pEzcZCTYPyE >}}


# For Next Time



::: callout-note
## Reminders and materials

:::


