---
title: "4\\. Cardiac Function and Metabolic Ceilings"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "The vertebrate heart and its regulation"
date: 2023-09-11
format: 
  html: default 
  pdf: default
categories: [module 4, week 4, cardiac function, cardiac cycle, cardiac regulation, MMR ]
---

This week we will learn more about cardiac morphology, function, and regulation. There are multiple very short (but important) readings, and some longer readings to skim. Donʻt worry about understanding every detail in the readings, but rather look over the discussion questions first and hunt through the readings for those topics, skimming over the rest. _These are going to be important topics for the next few labs._ 

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Monday we will finish heterothermy and start cardiac function. Wednesday cardiac regulation  \[[Heart Discussion Questions and readings](../../discussions/Discussion-Week4-heart-function.pdf)\] 
2. Friday we will discuss \[[Metabolic Celings](../../discussions/Discussion-Week4-metabolic-ceiling.pdf)\]
:::

### Announcements/Reminders

-  Please wear __comfortable shoes to lab__ for running up and down stairs.
-  HW1 solutions are posted on window of EDM101 lab.
-  HW2 due in class (hard copy preferred) or on Laulima by midnight.
-  \[[Design Background](../../projects/2023-09-06-design-background/index.qmd)\] Due __Wednesday in hardcopy__. 10 points. Chance to revise by Friday. 
-  Do discussion TEAMMATES eval, released each Friday, do by Monday.

### Week 4 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
| 1 |Adry| Krystal  | Sasha |
| 2 |  Logan B  |  Anna | Kirsten |
| 3 | Justin |  Maisie | Kylie |
| 4 | Mayuka  | Garrett  | Logan M |
| 5 |  Alvin | Richard  | Matt |
| 6 |  Morgan  | Christina  |  |

## Monday
   
- Finish up Heterothermy \[[questions 3,4](../../discussions/Discussion-Week3-temperature.pdf)\] \[[slide deck](../../powerpoints/4.Temperature.pdf)\] 
- Cardiac Cycle Q1,2 \[[slide deck](../../powerpoints/4.CardiacCycle.pdf)\]

## Wednesday

- Cardiac Function/Regulation Q3-6

## Friday 

- Paper discussion

# For Next Time



::: callout-note
## Reminders and materials

:::


